Added hard failure to pa11y-ci pipeline
* Added failure check

* Added a longer comment for pa11y failures.

* Temporarily removing axe

* Putting back axe

* Switching failure message to be in a group

* Trying error syntax for message.

* Adjusted the error text.

diff --git a/.github/workflows/pa11y.yml b/.github/workflows/pa11y.yml
--- a/.github/workflows/pa11y.yml
+++ b/.github/workflows/pa11y.yml
@@ -37,3 +37,10 @@ jobs:
         with:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           message: '```${{ steps.pa11y_output.outputs.content }}```'
+          
+      - name: Check for pa11y failures.
+        if: contains(steps.pa11y_output.outputs.content, 'errno 2')
+        run: |
+          echo "::error::The site is failing accessibility tests. Please review the comment in the pull request or the pa11y-ci step in the workflow for details."
+          exit 1
+
